# This is the build script for AppVeyor CI
# To build and test LightTwinSVM program on Windows OS
 
environment:

  matrix:
    
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.1"
      PYTHON_ARCH: "64"
      
install:
  # Check currrent working directory
  - "cd"

  # Prepend Python to The PATH
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  
  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  
  # Upgrade to the latest version of pip
  - "python -m pip install --upgrade pip"
  - "pip --version"
  
  # Install dependencies for testing LightTwinSVM
  - "pip install -r requirments.txt"
  
  # Install Cython for building extension module
  - "pip install Cython"
  
  # Clone Armadillo library for building C++ extension moudle
  # Armadillo is licensed under the Apache License, Version 2.0
  - "git clone https://github.com/mir-am/armadillo-code .\\ltsvm\\optimizer\\armadillo-code"
  
build_script:
  # Build C++ extension module (clipDCD optimizer)
  - ps: |
      pushd .\ltsvm\optimizer
      python setup.py build_ext --inplace
      popd
   
  # Adding BLAS and LAPACK libs to PATH   
  - ps: |
      $currentDir=(Get-Item -Path ".\").FullName
      $newPath=Join-Path $currentDir "ltsvm\optimizer\armadillo-code\lib_win64\"
      $env:Path += ';' + $newPath 
      #echo $env:Path
  
test_script:
  # Create a folder for saving test results
  - "mkdir result"
  - "python -m unittest discover -s tests"
