# LightTwinSVM Program - Simple and Fast
# Developer: Mir, A. (mir-am@hotmail.com)
# License: GNU General Public License v3.0

# Configuration file for building and testing LightTwinSVM on Travis CI
language: python

# Ubuntu 16.04 LTS & OS X
matrix:
  include:        
    - os: osx
      language: generic
      env: PYENV_VERSION=3.7.2

branches:
  only:
  - master


before_install:
  - chmod +x install-travisci.sh
  
install: ./install-travisci.sh


